"""initial schema

Revision ID: b531a949fc9b
Revises: 
Create Date: 2026-06-11 10:54:44.975267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b531a949fc9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjust_factor',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('divid_operate_date', sa.Date(), nullable=False),
    sa.Column('fore_adjust_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('back_adjust_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('adjust_factor', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'divid_operate_date')
    )
    op.create_table('data_watermark',
    sa.Column('code', sa.String(length=12), server_default='', nullable=False),
    sa.Column('data_type', sa.String(length=24), nullable=False),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=False),
    sa.Column('last_fetched_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code', 'data_type')
    )
    op.create_table('deposit_rate',
    sa.Column('pub_date', sa.Date(), nullable=False),
    sa.Column('demand_deposit_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fixed_deposit_rate_3month', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fixed_deposit_rate_6month', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fixed_deposit_rate_1year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fixed_deposit_rate_2year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fixed_deposit_rate_3year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fixed_deposit_rate_5year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('installment_fixed_deposit_rate_1year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('installment_fixed_deposit_rate_3year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('installment_fixed_deposit_rate_5year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pub_date')
    )
    op.create_table('dividend',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('plan_announce_date', sa.Date(), nullable=False),
    sa.Column('year_type', sa.String(length=7), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('regist_date', sa.Date(), nullable=True),
    sa.Column('operate_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('cash_ps_before_tax', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cash_ps_after_tax', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('stocks_ps', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('reserve_to_stock_ps', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'plan_announce_date', 'year_type')
    )
    op.create_table('fetch_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_report',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'report_type', 'stat_date')
    )
    op.create_table('index_constituent',
    sa.Column('index_code', sa.String(length=8), nullable=False),
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('code_name', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('index_code', 'snap_date', 'code')
    )
    op.create_table('kline',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('frequency', sa.CHAR(length=1), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('preclose', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('turn', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('pct_chg', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('trade_status', sa.SmallInteger(), nullable=True),
    sa.Column('is_st', sa.Boolean(), nullable=True),
    sa.Column('pe_ttm', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('pb_mrq', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('ps_ttm', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('pcf_ncf_ttm', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'frequency', 'trade_date')
    )
    op.create_table('kline_minute',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('frequency', sa.SmallInteger(), nullable=False),
    sa.Column('bar_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'frequency', 'bar_time'),
    postgresql_partition_by='RANGE (bar_time)'
    )
    op.create_table('loan_rate',
    sa.Column('pub_date', sa.Date(), nullable=False),
    sa.Column('loan_rate_6month', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('loan_rate_6month_to_1year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('loan_rate_1year_to_3year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('loan_rate_3year_to_5year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('loan_rate_above_5year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('mortgage_rate_below_5year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('mortgage_rate_above_5year', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pub_date')
    )
    op.create_table('money_supply_month',
    sa.Column('stat_year', sa.SmallInteger(), nullable=False),
    sa.Column('stat_month', sa.SmallInteger(), nullable=False),
    sa.Column('m0_month', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('m0_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('m0_chain_relative', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('m1_month', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('m1_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('m1_chain_relative', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('m2_month', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('m2_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('m2_chain_relative', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stat_year', 'stat_month')
    )
    op.create_table('money_supply_year',
    sa.Column('stat_year', sa.SmallInteger(), nullable=False),
    sa.Column('m0_year', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('m0_year_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('m1_year', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('m1_year_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('m2_year', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('m2_year_yoy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stat_year')
    )
    op.create_table('required_reserve_ratio',
    sa.Column('pub_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('big_institutions_ratio_pre', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('big_institutions_ratio_after', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('medium_institutions_ratio_pre', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('medium_institutions_ratio_after', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('pub_date', 'effective_date')
    )
    op.create_table('stock_basic',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('code_name', sa.String(length=64), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('out_date', sa.Date(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('stock_industry',
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('code_name', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('industry_classification', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('snap_date', 'code')
    )
    op.create_table('stock_list_snapshot',
    sa.Column('snap_date', sa.Date(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('code_name', sa.String(length=64), nullable=True),
    sa.Column('trade_status', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('snap_date', 'code')
    )
    op.create_table('trade_calendar',
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('calendar_date')
    )
    # ### end Alembic commands ###

    # ── 手写部分（autogenerate 不支持） ──

    # kline_minute 年度分区：2023（分钟线回填起点）~ 2027，年界按北京时间对齐；
    # DEFAULT 分区兜底超范围数据，避免写入报错（每年由运维/beat 预建下一年分区）
    for year in range(2023, 2028):
        op.execute(
            f"CREATE TABLE kline_minute_y{year} PARTITION OF kline_minute "
            f"FOR VALUES FROM ('{year}-01-01 00:00:00+08') TO ('{year + 1}-01-01 00:00:00+08')"
        )
    op.execute("CREATE TABLE kline_minute_default PARTITION OF kline_minute DEFAULT")

    # 任务去重：进行中的同参数任务只允许一个（部分唯一索引）
    op.execute(
        "CREATE UNIQUE INDEX uq_fetch_task_active ON fetch_task (params_hash) "
        "WHERE status IN ('pending', 'running')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_calendar')
    op.drop_table('stock_list_snapshot')
    op.drop_table('stock_industry')
    op.drop_table('stock_basic')
    op.drop_table('required_reserve_ratio')
    op.drop_table('money_supply_year')
    op.drop_table('money_supply_month')
    op.drop_table('loan_rate')
    op.drop_table('kline_minute')
    op.drop_table('kline')
    op.drop_table('index_constituent')
    op.drop_table('financial_report')
    op.drop_table('fetch_task')
    op.drop_table('dividend')
    op.drop_table('deposit_rate')
    op.drop_table('data_watermark')
    op.drop_table('adjust_factor')
    # ### end Alembic commands ###
