// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockData.Mcp.Data;

#nullable disable

namespace StockData.Mcp.Data.Migrations
{
    [DbContext(typeof(StockDataDbContext))]
    [Migration("20260625024046_AddRemainingTables")]
    partial class AddRemainingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockData.Mcp.Data.Entities.AdjustFactor", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("DividOperateDate")
                        .HasColumnType("date")
                        .HasColumnName("divid_operate_date");

                    b.Property<decimal?>("AdjustFactorValue")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("adjust_factor");

                    b.Property<decimal>("BackAdjustFactor")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("back_adjust_factor");

                    b.Property<decimal>("ForeAdjustFactor")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("fore_adjust_factor");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Code", "DividOperateDate");

                    b.ToTable("adjust_factor");
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.DataWatermark", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(12)")
                        .HasDefaultValue("")
                        .HasColumnName("code");

                    b.Property<string>("DataType")
                        .HasColumnType("character varying(24)")
                        .HasColumnName("data_type");

                    b.Property<DateOnly?>("FirstDate")
                        .HasColumnType("date")
                        .HasColumnName("first_date");

                    b.Property<DateOnly>("LastDate")
                        .HasColumnType("date")
                        .HasColumnName("last_date");

                    b.Property<DateTimeOffset>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fetched_at");

                    b.HasKey("Code", "DataType");

                    b.ToTable("data_watermark", (string)null);
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.Dividend", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<DateOnly>("PlanAnnounceDate")
                        .HasColumnType("date")
                        .HasColumnName("plan_announce_date");

                    b.Property<string>("YearType")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("year_type");

                    b.Property<decimal?>("CashPsAfterTax")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cash_ps_after_tax");

                    b.Property<decimal?>("CashPsBeforeTax")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("cash_ps_before_tax");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateOnly?>("OperateDate")
                        .HasColumnType("date")
                        .HasColumnName("operate_date");

                    b.Property<DateOnly?>("PayDate")
                        .HasColumnType("date")
                        .HasColumnName("pay_date");

                    b.Property<DateOnly?>("RegistDate")
                        .HasColumnType("date")
                        .HasColumnName("regist_date");

                    b.Property<decimal?>("ReserveToStockPs")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("reserve_to_stock_ps");

                    b.Property<decimal?>("StocksPs")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("stocks_ps");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Code", "PlanAnnounceDate", "YearType");

                    b.ToTable("dividend");
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.FinancialReport", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<string>("ReportType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("report_type");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date")
                        .HasColumnName("stat_date");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics");

                    b.Property<DateOnly?>("PubDate")
                        .HasColumnType("date")
                        .HasColumnName("pub_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Code", "ReportType", "StatDate");

                    b.ToTable("financial_report");
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.IndexConstituent", b =>
                {
                    b.Property<string>("IndexCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("index_code");

                    b.Property<DateOnly>("SnapDate")
                        .HasColumnType("date")
                        .HasColumnName("snap_date");

                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<string>("CodeName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("IndexCode", "SnapDate", "Code");

                    b.ToTable("index_constituent");
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.Kline", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<string>("Frequency")
                        .HasColumnType("character(1)")
                        .HasColumnName("frequency");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("Close")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("close");

                    b.Property<decimal?>("High")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("high");

                    b.Property<bool?>("IsSt")
                        .HasColumnType("boolean")
                        .HasColumnName("is_st");

                    b.Property<decimal?>("Low")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("low");

                    b.Property<decimal?>("Open")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("open");

                    b.Property<decimal?>("PbMrq")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("pb_mrq");

                    b.Property<decimal?>("PcfNcfTtm")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("pcf_ncf_ttm");

                    b.Property<decimal?>("PctChg")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("pct_chg");

                    b.Property<decimal?>("PeTtm")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("pe_ttm");

                    b.Property<decimal?>("Preclose")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("preclose");

                    b.Property<decimal?>("PsTtm")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("ps_ttm");

                    b.Property<short?>("TradeStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("trade_status");

                    b.Property<decimal?>("Turn")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("turn");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Code", "Frequency", "TradeDate");

                    b.ToTable("kline", (string)null);
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.StockBasic", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<string>("CodeName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_name");

                    b.Property<DateOnly?>("IpoDate")
                        .HasColumnType("date")
                        .HasColumnName("ipo_date");

                    b.Property<DateOnly?>("OutDate")
                        .HasColumnType("date")
                        .HasColumnName("out_date");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short?>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Code");

                    b.ToTable("stock_basic");
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.StockIndustry", b =>
                {
                    b.Property<DateOnly>("SnapDate")
                        .HasColumnType("date")
                        .HasColumnName("snap_date");

                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<string>("CodeName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_name");

                    b.Property<string>("Industry")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("industry");

                    b.Property<string>("IndustryClassification")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("industry_classification");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SnapDate", "Code");

                    b.ToTable("stock_industry");
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.StockListSnapshot", b =>
                {
                    b.Property<DateOnly>("SnapDate")
                        .HasColumnType("date")
                        .HasColumnName("snap_date");

                    b.Property<string>("Code")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<string>("CodeName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_name");

                    b.Property<bool?>("TradeStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("trade_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SnapDate", "Code");

                    b.ToTable("stock_list_snapshot");
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.TradeCalendar", b =>
                {
                    b.Property<DateOnly>("CalendarDate")
                        .HasColumnType("date")
                        .HasColumnName("calendar_date");

                    b.Property<bool>("IsTradingDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trading_day");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CalendarDate");

                    b.ToTable("trade_calendar");
                });
#pragma warning restore 612, 618
        }
    }
}
