// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockData.Mcp.Data;

#nullable disable

namespace StockData.Mcp.Data.Migrations
{
    [DbContext(typeof(StockDataDbContext))]
    partial class StockDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockData.Mcp.Data.Entities.DataWatermark", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(12)")
                        .HasDefaultValue("")
                        .HasColumnName("code");

                    b.Property<string>("DataType")
                        .HasColumnType("character varying(24)")
                        .HasColumnName("data_type");

                    b.Property<DateOnly?>("FirstDate")
                        .HasColumnType("date")
                        .HasColumnName("first_date");

                    b.Property<DateOnly>("LastDate")
                        .HasColumnType("date")
                        .HasColumnName("last_date");

                    b.Property<DateTimeOffset>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fetched_at");

                    b.HasKey("Code", "DataType");

                    b.ToTable("data_watermark", (string)null);
                });

            modelBuilder.Entity("StockData.Mcp.Data.Entities.Kline", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<string>("Frequency")
                        .HasColumnType("character(1)")
                        .HasColumnName("frequency");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("Close")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("close");

                    b.Property<decimal?>("High")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("high");

                    b.Property<bool?>("IsSt")
                        .HasColumnType("boolean")
                        .HasColumnName("is_st");

                    b.Property<decimal?>("Low")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("low");

                    b.Property<decimal?>("Open")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("open");

                    b.Property<decimal?>("PbMrq")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("pb_mrq");

                    b.Property<decimal?>("PcfNcfTtm")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("pcf_ncf_ttm");

                    b.Property<decimal?>("PctChg")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("pct_chg");

                    b.Property<decimal?>("PeTtm")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("pe_ttm");

                    b.Property<decimal?>("Preclose")
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("preclose");

                    b.Property<decimal?>("PsTtm")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("ps_ttm");

                    b.Property<short?>("TradeStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("trade_status");

                    b.Property<decimal?>("Turn")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("turn");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Code", "Frequency", "TradeDate");

                    b.ToTable("kline", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
